function createfigure_fit(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 08-Mar-2018 23:03:50

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.130714285714286 0.116904761904762 0.774285714285714 0.808095238095238]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','data','MarkerSize',10,'Marker','+','LineWidth',2,...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'DisplayName','fitted curve','LineWidth',2,'Color',[1 0 0]);

% Create xlabel
xlabel({'Buffer capacity (second)'});

% Create ylabel
ylabel({'Outage rate'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',17,'LineWidth',2,'XGrid','on','YGrid','on');
% Create legend
legend(axes1,'show');

